@startuml
left to right direction
actor "Administrador" as Admin
actor "Seguridad" as Seguridad
actor "Limpieza" as Limpieza
actor "Departamento" as Departamento
actor "Mantenimiento" as Mantenimiento
actor "Empleado" as Empleado
actor "Usuario"

package "Gestión de Usuarios y Administradores" {
    usecase "Iniciar sesión" as IniciarSesion
    usecase "Verificación 2FA" as Verificacion2FA
    usecase "Recuperar contraseña" as RecuperarContraseña
    usecase "Gestionar cuenta" as GestionarCuenta
    usecase "Crear cuenta" as CrearCuenta
    usecase "Actualizar cuenta" as ActualizarCuenta
    usecase "Desactivar cuenta" as DesactivarCuenta
}
' Asociación entre actores y casos de uso
Admin --> GestionarCuenta
Usuario --> IniciarSesion
Departamento --> GestionarCuenta

' Generalización
Usuario <|-- Empleado
Usuario <|-- Admin
Usuario <|-- Departamento
Empleado <|-- Seguridad
Empleado <|-- Limpieza  
Empleado <|-- Mantenimiento

GestionarCuenta <|-- CrearCuenta
GestionarCuenta <|-- ActualizarCuenta
GestionarCuenta <|-- DesactivarCuenta

' Relaciones include y extend
GestionarCuenta ..> Verificacion2FA : <<include>>
IniciarSesion .> Verificacion2FA : <<include>>
IniciarSesion <. RecuperarContraseña : <<extend>>
@enduml