/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RIBZ
 */
public class FrmMenuBar extends javax.swing.JFrame {

     private CardLayout cardLayout;  // Declaración a nivel de clase

    public FrmMenuBar() {
        initComponents();
            this.setSize(1280,720);
            this.setLocationRelativeTo(null);
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        inicializacionItemsMenuBar();

        // Asignar CardLayout al PanelPrincipal
        cardLayout = (CardLayout) PanelPrincipal.getLayout();
        
        // Agregar acción a los elementos del menú
        jMenuIUGuardar.addActionListener((ActionEvent e) -> {
            cambiarPanel("card3");  // Mostrar PanelGuardar
        });

        jMenuIUBuscar.addActionListener((ActionEvent e) -> {
            cambiarPanel("card2");  // Mostrar PanelBuscar
        });
        
        jMenuIUModificar.addActionListener((ActionEvent e) -> {
            cambiarPanel("card5");  // Mostrar PanelBuscar
        });
        
        jMenuIUEliminar.addActionListener((ActionEvent e) -> {
            cambiarPanel("card6");  // Mostrar PanelBuscar
        });
    }

    private void inicializacionItemsMenuBar() {
        jMenuUsuario = new javax.swing.JMenu();        
        jMenuIUGuardar = new javax.swing.JMenuItem();
        jMenuIUBuscar = new javax.swing.JMenuItem();
        jMenuIUModificar = new javax.swing.JMenuItem();
        jMenuIUEliminar = new javax.swing.JMenuItem();

        jMenuUsuario.setText("Usuario");
        jMenuUsuario.setIcon(obtenerImagen(logo_Usuario));
        jMenuUsuario.setOpaque(true);
        jMenuUsuario.setBackground(mColorFondoMenu);
        jMenuUsuario.setForeground(Color.WHITE);
        jMenuUsuario.setMaximumSize(new java.awt.Dimension(Short.MAX_VALUE, 50)); 
        
        jMenuIUGuardar.setText("Guardar");
        jMenuIUBuscar.setText("Buscar");
        jMenuIUModificar.setText("Modificar");
        jMenuIUEliminar.setText("Eliminar");
        jMenuUsuario.add(jMenuIUGuardar);
        jMenuUsuario.add(jMenuIUBuscar);
        jMenuUsuario.add(jMenuIUModificar);
        jMenuUsuario.add(jMenuIUEliminar);
        
        mbMenuBar.add(jMenuUsuario);
        mbMenuBar.setPreferredSize(new java.awt.Dimension(this.getWidth(), 50)); // Ancho igual al frame y altura 50
        // Crear una nueva fuente
        java.awt.Font font = new java.awt.Font("Arial", java.awt.Font.BOLD, 16); // Tamaño de fuente 14 y estilo negrita

        // Establecer la fuente para cada JMenu
        jMenuUsuario.setFont(font);
        java.awt.Font font1 = new java.awt.Font("Arial", java.awt.Font.ROMAN_BASELINE, 16); // Tamaño de fuente 14 y estilo negrita
        jMenuIUGuardar.setFont(font1);
        jMenuIUBuscar.setFont(font1);
        jMenuIUModificar.setFont(font1);
        jMenuIUEliminar.setFont(font1);

    }

    private void cambiarPanel(String nombrePanel) {
        cardLayout.show(PanelPrincipal, nombrePanel);
    }

    private Icon obtenerImagen(String ruta){
        return new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(30, 30, 0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelUsuarios = new javax.swing.JPanel();
        PanelGuardar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanerBuscar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelModificar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mbMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(128, 105, 70));
        PanelPrincipal.setLayout(new java.awt.CardLayout());

        PanelUsuarios.setBackground(new java.awt.Color(80, 200, 120));
        PanelUsuarios.setLayout(null);
        PanelPrincipal.add(PanelUsuarios, "card2");

        PanelGuardar.setBackground(new java.awt.Color(89, 116, 112));
        PanelGuardar.setForeground(new java.awt.Color(0, 0, 0));
        PanelGuardar.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Source Code Pro Light", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guardar ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelGuardar.add(jLabel1);
        jLabel1.setBounds(440, 270, 390, 80);

        PanelPrincipal.add(PanelGuardar, "card3");

        PanerBuscar.setBackground(new java.awt.Color(85, 107, 47));
        PanerBuscar.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Source Code Pro Light", 0, 48)); // NOI18N
        jLabel2.setText("Buscar");
        PanerBuscar.add(jLabel2);
        jLabel2.setBounds(520, 240, 320, 190);

        PanelPrincipal.add(PanerBuscar, "card2");

        PanelModificar.setBackground(new java.awt.Color(96, 128, 117));
        PanelModificar.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Source Code Pro ExtraLight", 0, 48)); // NOI18N
        jLabel3.setText("Modificar");
        PanelModificar.add(jLabel3);
        jLabel3.setBounds(480, 240, 310, 150);

        PanelPrincipal.add(PanelModificar, "card5");

        PanelEliminar.setBackground(new java.awt.Color(24, 60, 34));
        PanelEliminar.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Source Code Pro ExtraLight", 0, 48)); // NOI18N
        jLabel4.setText("Eliminar");
        PanelEliminar.add(jLabel4);
        jLabel4.setBounds(530, 260, 390, 160);

        PanelPrincipal.add(PanelEliminar, "card6");

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);
        setJMenuBar(mbMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmMenuBar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEliminar;
    public javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelModificar;
    public javax.swing.JPanel PanelPrincipal;
    public javax.swing.JPanel PanelUsuarios;
    private javax.swing.JPanel PanerBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar mbMenuBar;
    // End of variables declaration//GEN-END:variables
 // Declaración de los menús
    public javax.swing.JMenu jMenuUsuario;
    public javax.swing.JMenuItem jMenuIUGuardar;
    public javax.swing.JMenuItem jMenuIUBuscar;
    public javax.swing.JMenuItem jMenuIUModificar;
    public javax.swing.JMenuItem jMenuIUEliminar;
    public String logo_Usuario= "/imagenes/clientes.png";

   
    public Color mColorFondoMenu= new Color(47, 79, 79);


    // End of variables declaration         
}