@startuml
abstract class EspacioComun {
    -id: int
    -nombre: String
    -capacidad: int
    +verificarDisponibilidad(): Boolean
    +actualizarEstado(estado: Boolean): void
}

class Parqueadero {
    -ubicacion: String
    -disponibilidad: bool
    +asignarEspacio(): void
    +liberarEspacio(): void
}

class Residente {
    -id: int
    -nombre: String
    -telefonoContacto: String
    +solicitarParqueadero(): void
    +notificarLlegadaProgramada(visitante: Visitante): void
}

class Guardia {
    -id: int
    -nombre: String
    -turno: String
    +vigilar(): void

}

class Visitante {
    -nombre: String
    -identificacion: String
    -detallesContacto: String
    -motivoVisita: String
}

class Reserva {
    -id: int
    -fecha: Date
    -hora: Time
    -departamento: Departamento
    +generarReserva(): void
    +cancelarReserva(): void
}

class RegistroEntrada {
    -fechaHora: DateTime
    -visitante: Visitante
    +registrarLlegada(): void
    +autorizar(estado: Boolean): void
    +guardarRegistro(): void

}

class Notificación {
    -tipo: String
    -contenido: String
    +enviarNotificacion(): void
}


class Vehiculo {
    -placa: String
    -modelo: String
    -color: String
    +obtenerDetalles(): String
}

EspacioComun <|-- Parqueadero
Residente "1" --> "0..*" Reserva : "realiza"
Reserva "1" --> "1" Parqueadero: "usa"
Residente "1" --> "0..*" RegistroEntrada : "solicita"

RegistroEntrada "1" --> "0..*" Notificación : "genera"
RegistroEntrada "1" --> "1..*" Visitante : "tiene"

Visitante "1" --> "0..1" Vehiculo : "posee"
Guardia "1" --> "0..*" RegistroEntrada : "supervisa"
Guardia "1" --> "0..*" Notificación : "envía"
@enduml
