@startuml

left to right direction

actor "Usuario" as usuarioNombre
actor "Administrador" as administradorNombre
actor "Empleado" as empleadoNombre
actor "Departamento" as departamentoNombre
package comunicacion{
package envioMensajes{
usecase "Enviar mensaje residente" as mensajeResidentes
usecase "Enviar mensaje directo" as mensajeDirecto
usecase "Enviar mensaje global" as mensajeGlobal
}

package comunicados{
usecase "Enviar comunicados a trabajadores" as comunicadoTrabajadores
}
package anuncioGeneral{
usecase "Modificar anuncio general" as modAnuncioGeneral
usecase "Eliminar anuncio general" as delAnuncioGeneral
usecase "Agregar anuncio general" as addAnuncioGeneral
}
package reportes{
usecase "Crear reporte" as creaReporte
}
}

administradorNombre -u-|> usuarioNombre
trabajadorNombre -u-|> usuarioNombre
residenteNombre -u-|> usuarioNombre


usuarioNombre --> mensajeResidentes
administradorNombre --> comunicadoTrabajadores
usuarioNombre --> mensajeGlobal
usuarioNombre --> mensajeDirecto


addAnuncioGeneral --> modAnuncioGeneral
addAnuncioGeneral --> delAnuncioGeneral
administradorNombre --> addAnuncioGeneral

residenteNombre --> comunicadoTrabajadores
administradorNombre --> creaReporte


@enduml
