@startuml

left to right direction

actor "Usuario" as usuarioNombre
actor "Administrador" as administradorNombre
actor "Empleado" as empleadoNombre
package comunicacion{
package envioMensajes{

usecase "Enviar mensaje directo" as mensajeDirecto
usecase "Enviar mensaje global" as mensajeGlobal
usecase "Recibir mensaje directo" as recibirmsjDirecto
usecase "Recibir mensaje global" as recibirmsjGlobal
}

package comunicados{
usecase "Enviar Comunicados Trabajadores" as comunicadoTrabajadores
usecase "Recibir Comunicados Trabajadores" as recibirComunicadoTrabajadores
}
package anuncioGeneral{
usecase "Modificar anuncio general" as modAnuncioGeneral
usecase "Eliminar anuncio general" as delAnuncioGeneral
usecase "Agregar anuncio general" as addAnuncioGeneral

}
package reportes{
usecase "Crear reporte de mensajes Empleados" as creaReporte
usecase "Visualizar reportes de mensajes Empleados" as visualizarReporte
}
}

administradorNombre -u-|> usuarioNombre
empleadoNombre -u-|> usuarioNombre

administradorNombre --> comunicadoTrabajadores
empleadoNombre --> recibirComunicadoTrabajadores
usuarioNombre --> mensajeGlobal
usuarioNombre --> mensajeDirecto
usuarioNombre --> recibirmsjGlobal
usuarioNombre --> recibirmsjDirecto

administradorNombre --> modAnuncioGeneral
administradorNombre --> delAnuncioGeneral
administradorNombre --> addAnuncioGeneral
administradorNombre --> visualizarReporte
administradorNombre --> creaReporte

@enduml
