@startuml
left to right direction
actor Departamento as C
Actor Administrador as A


usecase "Realizar un pago" as UC1
usecase "Editar y guardar el historial de pagos y multas" as guardar
usecase "Pago en efectivo" as UC1_1
usecase "Pago por transferencia bancaria" as UC1_2
usecase "Pago por depósito bancario" as UC1_3
usecase "Pago a cuotas" as UC1_4
usecase "Realizar un pago" as UC1
usecase "Visualizar historial de pagos y multas" as UC2
usecase "Recibir recordatorios y notificaciones" as UC3


usecase "Registrar un pago" as UC4
usecase "Registrar una multa" as UC5
usecase "Gestionar el historial de pagos y multas" as UC6
usecase "Editar y guardar el historial de pagos y multas" as UC6_1
usecase "Generar recordatorios y notificaciones" as UC7
usecase "Configurar métodos de pago" as UC8



C --> UC1
UC1 ..> guardar : <<include>>
UC1_1 <|-- UC1 
UC1_2 <|-- UC1  
UC1_3 <|-- UC1  
UC1_4 <|-- UC1  


C --> UC2
C --> UC3

A --> UC4
UC4 ..> UC6_1 : <<include>>
A --> UC5
UC5 ..> UC6_1: <<include>>
A --> UC6
UC6 ..> UC6_1: <<include>>
A --> UC7
A --> UC8
@enduml
