@startuml
' Encapsulación
skinparam classAttributeIconSize 0

class Usuario {
    - nombre: String
    - puesto: String
}

class Administrador {
}

class Empleado {

}

class ReporteMensaje {
    + crearReporte(contenido: String): void
    + visualizarReporte(idReporte: int): void
}


class Comunicado {
    + verificarAdministrador(puesto: String): boolean
}

class Mensaje{
    + enviarMensajeDirecto(contenido:String, destinatario: Usuario): void
    + recibirMensajeDirecto(Contenido: String, destinatario: Usuario): void
    + modificarAnuncioGeneral(puesto:String): void
    + eliminarAnuncioGeneral(puesto: String): void
}

interface IMensaje{
    +enviarMensaje(contenido:String): void
    +recibirMensaje(contenido:String): void
}


Usuario <|-- Empleado
Usuario <|-- Administrador
Administrador --> Comunicado: "<<use>>"
Empleado --> Comunicado: "<<use>>"
Usuario --> Mensaje: "<<use>>"
Administrador --> ReporteMensaje: "<<use>>"
Mensaje ..|> IMensaje: "<<implements>>"
Comunicado ..|> IMensaje: "<<implements>>"

note bottom of Comunicado: "Verificar solo administrador envía comunicado\nEmpleado solo recibe comunicado"
@enduml
