@startuml
left to right direction

actor "Departamento" as residente
actor "Guardia" as seguridad

package "Check-in" {
    usecase "Registrar Entrada" as registrarEntrada
    usecase "Recopilar Detalles del Visitante" as recopilarDetalles
    usecase "Notificar Llegada Programada" as notificarLlegada
    usecase "Mantener Registro Histórico" as mantenerRegistro
    usecase "Enviar Alerta Rápida" as enviarAlerta
    usecase "Coordinar Parqueadero de Visita" as coordinarParqueadero
}

package "Reservas de Espacios Comunes"{
   usecase "Reservar áreas comunes" as reservarAC
}

package "Comunicación"{
package envioMensajes{
usecase "enviarMensajeGlobal" as mensajeGlobal
}

}


registrarEntrada <.. recopilarDetalles : extend
registrarEntrada <.. notificarLlegada : extend
registrarEntrada <.. mantenerRegistro : extend


seguridad -down- enviarAlerta
seguridad -left- registrarEntrada

residente -- coordinarParqueadero

reservarAC <.up. coordinarParqueadero : include
mensajeGlobal <.up. enviarAlerta : include
@enduml