@startuml
left to right direction
actor Cliente

rectangle "Módulo de Reservas de Espacios Comunes" {
    usecase "Visualizar disponibilidad" as UC1
    usecase "Reservar áreas comunes" as UC2
    usecase "Cancelar reserva" as UC3

}

Cliente --> UC1
Cliente --> UC2
Cliente --> UC3
@enduml