@startuml
left to right direction
actor Residente
actor Administrador

package "Reserva de Espacios Comunes" {
    usecase "Visualizar disponibilidad" as VisualizarDisp
    usecase "Reservar área común" as ReservarArea
    usecase "Cancelar reserva" as CancelReserva
}

package "Comunicación" {
    usecase "Enviar solicitud de reserva" as EnviarSolicitud
    usecase "Revisar solicitud de reserva" as RevisarSolicitud
    usecase "Enviar aceptación de reserva" as EnviarAceptacion
    usecase "Enviar deuda de cuota" as EnviarDeuda
}

package "Pagos/Finanzas" {
    usecase "Verificar estado de cuotas" as VerEstadoCuota
}

Residente -- VisualizarDisp
VisualizarDisp <.right. ReservarArea: <<extend>>
Residente -- CancelReserva

ReservarArea ..> EnviarSolicitud: <<include>>
Administrador -up- EnviarDeuda
Administrador -up- EnviarAceptacion
Administrador -up- RevisarSolicitud
Administrador -right- VerEstadoCuota

ReservarArea <.. EnviarDeuda: <<extend>>
ReservarArea <.. EnviarAceptacion:  <<extend>>

@enduml