@startuml
left to right direction
actor Departamento

package "Reserva de Espacios Comunes" {
    usecase "Visualizar disponibilidad" as VisualizarDisp
    usecase "Reservar áreas comunes" as ReservarArea
    usecase "Cancelar reserva" as CancelReserva

}

Departamento --> VisualizarDisp
Departamento --> ReservarArea
Departamento --> CancelReserva
@enduml